#!/bin/bash

sudo apt-get update;
sudo apt install php7.0-dev -y;
sudo apt-get install php7.0-curl -y;
sudo apt-get install php7.0-gd -y;
sudo apt-get install php7.0-xml -y;
sudo apt-get install php7.0-mbstring;
sudo apt install git -y;
sudo apt-get install redis-server -y;
sudo apt-get install apache2 -y;
sudo apt-get install mysql-server -y;
sudo apt install composer -y;
sudo apt-get install dialog -y;
sudo apt install npm -y;
sudo apt-get install libapache2-mod-php7.0;
sudo apt-get install php7.0-mysql php7.0-mcrypt -y;
sudo apt-get install phpmyadmin php-gettext -y;
sudo ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf;
sudo a2enconf phpmyadmin.conf;
sudo systemctl restart apache2;
sudo chmod -R 777 /var/www/html;
sudo a2enmod proxy_fcgi setenvif;
sudo service apache2 restart;
sudo a2enmod rewrite;
sudo apt-get install playonlinux -y;
service apache2 restart;
ssh-keygen;
sudo apt install xclip;
sudo apt-get install build-essential libssl-dev -y;

sudo touch /var/www/html/index.html;
sudo chmod 777 /var/www/html/index.html;
sudo echo '<html><head><title>Welcome to Test!</title></head><body><h1>Succes! Virtual host is working!</h1></body></html>' > /var/www/html/index.html;
